# Generated by Django 5.0.2 on 2024-05-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'verbose_name': 'linea pedido', 'verbose_name_plural': 'linea pedidos'},
        ),
    ]
