# Generated by Django 5.0.2 on 2024-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='create',
            new_name='created',
        ),
    ]
