# Generated by Django 5.0.2 on 2024-04-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_create_categoria_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
